[package]
name = "typus_framework"
published-at = "0x708bf175f5a6f365dae45ff7684eb27e0597dcd0f142ba1999587825091c134f"
edition = "2024.alpha"

[dependencies.Pyth]
git = "https://github.com/Typus-Lab/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"
override = true

[dependencies.ScallopProtocol]
git = "https://github.com/Typus-Lab/sui-lending-protocol.git"
subdir = "contracts/protocol"
rev = "main"

[dependencies.Math]
git = "https://github.com/Typus-Lab/sui-lending-protocol.git"
subdir = "contracts/libs/math"
rev = "main"

[dependencies.suilend]
git = "https://github.com/Typus-Lab/suilend.git"
subdir = "contracts/suilend"
rev = "no-tests"

[dependencies.lending_core]
git = "https://github.com/Typus-Lab/navi-protocol-interface.git"
subdir = "lending_core"
rev = "main"

[dependencies.oracle]
git = "https://github.com/Typus-Lab/navi-protocol-interface.git"
subdir = "oracle"
rev = "main"

[dependencies.spool]
local = "../dependency/scallop/spool"

[addresses]
typus_framework = "0xb4f25230ba74837d8299e92951306100c4a532e8c48cc3d8828abe9b91c8b274"
