[package]
name = "typus_framework"
version = "1.0.0"
published-at = "0x8b009ac14a8401a270ba4e52341f0d141acc690d0cd82fd66a0c632ad64af22c"
edition = "2024.alpha"

[dependencies.Pyth]
git = "https://github.com/Typus-Lab/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "main"

[dependencies.ScallopProtocol]
git = "https://github.com/Typus-Lab/sui-lending-protocol.git"
subdir = "contracts/protocol"
rev = "main"

[dependencies.Math]
git = "https://github.com/Typus-Lab/sui-lending-protocol.git"
subdir = "contracts/libs/math"
rev = "main"

[dependencies.suilend]
git = "https://github.com/Typus-Lab/suilend.git"
subdir = "contracts/suilend"
rev = "no-tests"

[dependencies.lending_core]
git = "https://github.com/Typus-Lab/navi-smart-contracts.git"
subdir = "lending_core"
rev = "main"

[dependencies.oracle]
git = "https://github.com/Typus-Lab/navi-smart-contracts.git"
subdir = "oracle"
rev = "main"

[dependencies.spool]
local = "../dependency/scallop/spool"

[addresses]
typus_framework = "0xb4f25230ba74837d8299e92951306100c4a532e8c48cc3d8828abe9b91c8b274"
