[package]
name = "typus_dov"
published-at = "0xb8290daeb5204b3527cbc57637df55b12cc28d17ce08eadc910ae4cd8f9a695a"
edition = "2024.beta"

[dependencies.typus_nft]
local = "../typus_nft"

[dependencies.typus_oracle]
local = "../typus_oracle"

[dependencies.typus]
local = "../typus"

[dependencies.typus_framework]
local = "../typus_framework"

[addresses]
typus_dov = "0x321848bf1ae327a9e022ccb3701940191e02fa193ab160d9c0e49cd3c003de3a"
dov_fee_address = "0x03e3f1ca852358b50837758b5197fedf61e2ea69186c469595baa717560963f9"
