[package]
name = "typus_oracle"
published-at = "0x4658a0fbd9a234dfc87726addcbe1a602f27ce4513ecc1ec99e6d973c7bfb101"
edition = "2024.beta"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet"
override = true

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"
override = true

[dependencies.SupraOracle]
git = "https://github.com/Entropy-Foundation/dora-interface.git"
subdir = "sui/mainnet/supra_holder"
rev = "5fec42547d9d446cc3fdc01754721d5a044462b6"
override = true

[dependencies.SwitchboardStdLib]
git = "git@github.com:Typus-Lab/sui-sdk.git"
subdir = "move/mainnet/switchboard_std"
rev = "main"

[addresses]
typus_oracle = "0x855eb2d260ee42b898266e6df90bfd3c4ed821ccb253a352c159c223244a4b8a"
