[package]
name = "typus_oracle"
version = "0.7.2"
published-at = "0x4658a0fbd9a234dfc87726addcbe1a602f27ce4513ecc1ec99e6d973c7bfb101"
edition = "2024.beta"

[dependencies.Pyth]
git = "https://github.com/Typus-Lab/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"

[dependencies.SupraOracle]
git = "https://github.com/Typus-Lab/dora-interface.git"
subdir = "sui/mainnet/supra_holder"
rev = "master"

[dependencies.SwitchboardStdLib]
git = "https://github.com/Typus-Lab/sui-sdk.git"
subdir = "move/mainnet/switchboard_std"
rev = "main"

[addresses]
typus_oracle = "0x855eb2d260ee42b898266e6df90bfd3c4ed821ccb253a352c159c223244a4b8a"